workflows:
  build_and_deploy:
    name: Build and Deploy
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.yourcompany.yourapp"  # Replace with your iOS Bundle ID
        PACKAGE_NAME: "com.yourcompany.yourapp"  # Replace with your Android Package Name
        FIREBASE_APP_ID: "1:1234567890:android:abc123"  # Replace with your Firebase App ID
      groups:
        - app_store_credentials  # iOS API Key group in Codemagic
        - firebase_credentials  # Firebase credentials group in Codemagic
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          xcode-project use-profiles
          flutter build ios --release --no-codesign
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk  # Android artifact
      - build/ios/iphoneos/*.ipa   # iOS artifact
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY  # Use the Codemagic API key
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        release_type: beta
      firebase:
        firebase_service_account: $FIREBASE_CREDENTIALS
        groups:
          - internal-testers
        artifact_type: "apk"
